ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPSConnectionPool(host='www.ohcsg.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EA50640310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPConnectionPool(host='m.didaxiaoshuo.cc', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50986490>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPConnectionPool(host='gl.mozhua.net_', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50659490>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPSConnectionPool(host='www.lu85.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EA50659C40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPConnectionPool(host='www.huayuewenku.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50659040>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='3hao3.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50659520>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPConnectionPool(host='www.34zw.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50640B50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPSConnectionPool(host='www.tangzhekan8.xyz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1123)')))
ERROR:root:HTTPConnectionPool(host='m.2shubao.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50640B50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPSConnectionPool(host='www.200shucheng.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EA50640880>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPSConnectionPool(host='www.wanwenhui.com-by', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EA360C1730>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPSConnectionPool(host='www.govtz.com-by', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EA506405B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='m.nokiacn.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50640820>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPSConnectionPool(host='m.pipimov.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EA506405B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='m.67manhua.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50640820>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='m.llmanhua.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA506405B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='mh.59kan.vip', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50640820>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='www.fmhuaa.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA506405B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='www.qkmh5.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50640820>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='www.72qier.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA506405B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPSConnectionPool(host='www.17kmanhua.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EA50640820>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPConnectionPool(host='www.xiudm.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50640250>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPSConnectionPool(host='www.ishuhui.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1123)')))
ERROR:root:HTTPSConnectionPool(host='m.tohomh123.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)')))
ERROR:root:HTTPSConnectionPool(host='m.mh160.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EA50640A30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='m.1997666.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50640250>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPConnectionPool(host='m.manhuaduo.cn', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50986C10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPConnectionPool(host='xqmanhua.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50986880>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='www.haomh.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50986A60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPSConnectionPool(host='m.manhuami.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EA506584F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='m.shuamanhua.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA506574F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPConnectionPool(host='www.zisu88.vip', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA506405E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPConnectionPool(host='www.kankan.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA33CE3E50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPConnectionPool(host='7.emoyiyi.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA506405E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPSConnectionPool(host='www.16book1.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EA506634C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPSConnectionPool(host='www.yq-888.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1123)')))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPConnectionPool(host='www.ibqg5200.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50986F70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPSConnectionPool(host='www.lansezw.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EA360C1DF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='m.1909.tv', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50640B80>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='m.wztmw.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50640820>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPConnectionPool(host='www.1909.tv', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50640850>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPSConnectionPool(host='m.iqing.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EA50640D90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='m.beidouxin.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50640D00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPSConnectionPool(host='www.yesehan.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1123)')))
ERROR:root:HTTPConnectionPool(host='www.es123.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50986F70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPSConnectionPool(host='www.xs222.tw-by', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EA50986F40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPSConnectionPool(host='www.37shuwu.com-by', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EA50986C10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='m.tmwk8.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50986CA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPSConnectionPool(host='m.88dush.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EA5065F550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPSConnectionPool(host='www.uctxt.com-by', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EA5065F370>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPSConnectionPool(host='www.geilimei.cc-', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EA5065F580>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPSConnectionPool(host='u.76xs.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EA5065FCA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='www.1980xx.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA5065F760>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPSConnectionPool(host='www.shubaou.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EA5065F850>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPSConnectionPool(host='www.suimeng.la', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)')))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPConnectionPool(host='www.269n.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50986850>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPConnectionPool(host='xs.23yue.cn', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50986F40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='api.gdugm.cn', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50986820>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='m.66rou.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50986220>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='www.biquge.cm-by', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50986580>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPConnectionPool(host='m.baikg.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50640A00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPSConnectionPool(host='bl-novel.in', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1123)')))
ERROR:root:HTTPSConnectionPool(host='m.yssm.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1123)')))
ERROR:root:HTTPConnectionPool(host='www.khxs8.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50640280>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPSConnectionPool(host='www.daai99.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EA506405E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='m.kanshuge.la', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50640F40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='www.hsba.cc', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50640A60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPConnectionPool(host='book.hostfans.cn', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA509862B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='www.zisu8.cc', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA509867F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPSConnectionPool(host='www.1200ksw.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EA50986CA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPSConnectionPool(host='m.miaobige.com.tw', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EA50986F70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPSConnectionPool(host='m.moyuxiaoshuo.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EA50986970>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='www.t5xs.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50986D60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPSConnectionPool(host='www.23wxw.cc', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EA509868B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='m.3zxs.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA509865E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='www.2shubao.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA509864F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPSConnectionPool(host='www.miaobige.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EA50986EE0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPSConnectionPool(host='www.suimeng.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)')))
ERROR:root:HTTPConnectionPool(host='www.akxs.tw', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50986550>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPSConnectionPool(host='www.cwems.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1123)')))
ERROR:root:HTTPSConnectionPool(host='www.kenxingw.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EA5065FAC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='www.wandouxs.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA5065F6A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPSConnectionPool(host='www.88dush.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EA5065FF40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='m.34zw.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA5065F760>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPConnectionPool(host='www.wenchangshuyuan.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50986850>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPSConnectionPool(host='m.lzzxs.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EA50640910>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPConnectionPool(host='www.karto.cn', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50640A30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='m.zhenshuge.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50640B20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='www.sanhao33.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50640580>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='www.yznnw.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50640310>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPConnectionPool(host='www.01wxw.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA360C1670>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPSConnectionPool(host='www.kuaiyankanshu.net', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError("hostname 'www.kuaiyankanshu.net' doesn't match either of '36mh.com', 'm.36mh.com', 'www.36mh.com'")))
ERROR:root:HTTPConnectionPool(host='www.kanshuge.la', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50640280>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPSConnectionPool(host='www.4wxw.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)')))
ERROR:root:HTTPConnectionPool(host='www.365xs.cc', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50640280>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPSConnectionPool(host='www.suimeng.com-by', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EA506406D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='www.3zxs.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50640280>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='www.17book.cc', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA506406D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPSConnectionPool(host='www.biqugezw.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1123)')))
ERROR:root:HTTPSConnectionPool(host='www.ab74.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001EA506406D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='www.cnsxw.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001EA50640280>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='3hao3.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F6CB444820>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='7.emoyiyi.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F6CB444BB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPConnectionPool(host='gl.mozhua.net_', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F6CA07F7C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPConnectionPool(host='m.1997666.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F6CA0869A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='m.2shubao.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F6CA086400>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='m.67manhua.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F6CA086580>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPConnectionPool(host='m.didaxiaoshuo.cc', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F6CA0867F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPConnectionPool(host='m.llmanhua.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F6B068D6A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='m.manhuaduo.cn', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F6CA086280>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPSConnectionPool(host='m.manhuami.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F6CA086190>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPSConnectionPool(host='m.mh160.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F6CA0865B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='m.nokiacn.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F6CA086100>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPSConnectionPool(host='m.pipimov.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F6CB444850>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPConnectionPool(host='m.shuamanhua.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F6CA08F1F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPSConnectionPool(host='m.tohomh123.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)')))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPConnectionPool(host='mh.59kan.vip', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F6CA08F730>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPSConnectionPool(host='www.16book1.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F6CA086D60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPSConnectionPool(host='www.17kmanhua.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F6CA0867C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPSConnectionPool(host='www.200shucheng.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F6CA086220>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPConnectionPool(host='www.34zw.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F6B0B8DDC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPConnectionPool(host='www.72qier.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F6CA08FEE0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPConnectionPool(host='www.fmhuaa.net', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F6CB444F70>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPSConnectionPool(host='www.govtz.com-by', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F6B0B8DD00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:HTTPConnectionPool(host='www.haomh.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F6B0B8DD90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPConnectionPool(host='www.huayuewenku.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F6CA086760>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPConnectionPool(host='www.ibqg5200.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F6CA086490>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPSConnectionPool(host='www.ishuhui.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1123)')))
ERROR:root:HTTPConnectionPool(host='www.kankan.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F6CA086100>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPSConnectionPool(host='www.lu85.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F6CB444730>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPSConnectionPool(host='www.ohcsg.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001F6CA08F610>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPConnectionPool(host='www.qkmh5.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F6CA08F670>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:HTTPSConnectionPool(host='www.tangzhekan8.xyz', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1123)')))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
ERROR:root:('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
